import { chromium } from 'playwright-core';
const OUT = '/tmp/claude-0/-home-user-Airductmiami/f6adc180-da13-54f8-a7a4-06b618c777de/scratchpad';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--no-sandbox'] });
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
const bad = [];
p.on('response', r => { if (r.url().includes('/images/') && r.status() !== 200) bad.push(r.status() + ' ' + r.url()); });
await p.goto('http://127.0.0.1:4321/', { waitUntil: 'networkidle' });
await p.waitForTimeout(3000);
const imgs = await p.evaluate(() => [...document.querySelectorAll('.door-card img')].map(i => ({ ok: i.complete && i.naturalWidth > 0, w: i.naturalWidth })));
console.log('door images loaded:', JSON.stringify(imgs));
console.log('failed image requests:', bad.length ? bad : 'none');
console.log('overflow:', await p.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth));
await p.locator('.emergency-band').scrollIntoViewIfNeeded(); await p.waitForTimeout(600);
await p.screenshot({ path: `${OUT}/final-emerg.png` });
await p.locator('.doors-band').scrollIntoViewIfNeeded(); await p.waitForTimeout(800);
await p.screenshot({ path: `${OUT}/final-doors.png` });
const m = await b.newPage({ viewport: { width: 390, height: 844 } });
await m.goto('http://127.0.0.1:4321/', { waitUntil: 'networkidle' });
await m.waitForTimeout(2500);
console.log('mobile overflow:', await m.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth));
await b.close();
